server:
  port: 8080

spring:
  application:
    name: health-check-service
  mvc:
    async:
      request-timeout: 10000

logging:
  level:
    root: INFO
    com.gideon.healthcheck: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"